openapi: 3.0.0
info:
  title: Sample API Spec
  version: 1.0.0

security:
  - bearerAuth: []

paths:
  /auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Login success response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/APIResponseLogin"

  /users:
    get:
      summary: Get user list
      security:
        - bearerAuth: [] # optional (필요 시 per-path로도 가능)
      responses:
        "200":
          description: List of users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/APIResponseUsers"

    post:
      summary: Create user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreateRequest"
      security:
        - bearerAuth: [] # optional (필요 시 per-path로도 가능)
      responses:
        "201":
          description: User created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/APIResponseUser"

components:
  schemas:
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string

    LoginData:
      type: object
      required:
        - token
        - user
      properties:
        token:
          type: string
        user:
          $ref: "#/components/schemas/User"

    User:
      type: object
      required:
        - id
        - name
        - email
        - role
        - companyId
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        role:
          type: string
        companyId:
          type: integer

    UserCreateRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string

    APIResponse:
      type: object
      required:
        - success
      properties:
        success:
          type: boolean
        data:
          type: object
          nullable: true
        error:
          type: string
        message:
          type: string

    APIResponseUsers:
      allOf:
        - $ref: "#/components/schemas/APIResponse"
        - type: object
          properties:
            data:
              type: array
              items:
                $ref: "#/components/schemas/User"

    APIResponseUser:
      allOf:
        - $ref: "#/components/schemas/APIResponse"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/User"

    APIResponseLogin:
      allOf:
        - $ref: "#/components/schemas/APIResponse"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/LoginData"
