openapi: 3.0.10
info:
  title: Sample API Spec
  version: 1.0.0

# 서버 정보 참조
servers:
  - url: https://your-api-base-url.com
    description: Production server

# 보안 정의 참조
#security:
#  - bearerAuth: []

# 경로 참조
paths:
  /auth/login:
    $ref: "./paths/auth.yaml#/login"
  /auth/refresh:
    $ref: "./paths/auth.yaml#/refresh"
  /auth/logout:
    $ref: "./paths/auth.yaml#/logout"
  /auth/validate:
    $ref: "./paths/auth.yaml#/validate"
  /api-keys:
    $ref: "./paths/api-keys.yaml#/api-keys"
  /api-keys/{key}:
    $ref: "./paths/api-keys.yaml#/api-key"
  /azure-stroage/sas-token:
    $ref: "./paths/azure-storage.yaml#/sas-token"
  /azure-storage/containers/{containerName}/blobs:
    $ref: "./paths/azure-storage.yaml#/containers/blobs"
  #/azure-ai-search/indexers:
  #  $ref: "./paths/azure-ai-search.yaml#/indexers"
  #/azure-ai-search/indexers/{indexer-name}:
  #  $ref: "./paths/azure-ai-search.yaml#/indexer"
  #/azure-ai-search/indexers/{indexer-name}/run:
  #  $ref: "./paths/azure-ai-search.yaml#/indexer-run"
  #/azure-ai-search/indexers/{indexer-name}/reset:
  #  $ref: "./paths/azure-ai-search.yaml#/indexer-reset"
  /chat/completions:
    $ref: "./paths/chat.yaml#/completions"
  /companies/{id}:
    $ref: "./paths/companies.yaml#/company"
  /companies:
    $ref: "./paths/companies.yaml#/companies"
  /rag/document/upload:
    $ref: "./paths/rag.yaml#/uploadDocument"
  /rag/query:
    $ref: "./paths/rag.yaml#/query"
  /rag/index/update:
    $ref: "./paths/rag.yaml#/indexUpdate"
  /rag/index/status:
    $ref: "./paths/rag.yaml#/indexStatus"
  /rag/sessions/{id}:
    $ref: "./paths/rag.yaml#/session"
  /rag/sessions:
    $ref: "./paths/rag.yaml#/sessions"
  /users/{id}:
    $ref: "./paths/users.yaml#/user"
  /users:
    $ref: "./paths/users.yaml#/users"
  /llm-endpoints:
    $ref: "./paths/llm-endpoints.yaml#/llm-endpoints"
  /llm-endpoints/{id}:
    $ref: "./paths/llm-endpoints.yaml#/llm-endpoint"
  /llm-endpoints/{id}/test:
    $ref: "./paths/llm-endpoints.yaml#/llm-endpoint-test"
  /llm-endpoints/{id}/health:
    $ref: "./paths/llm-endpoints.yaml#/llm-endpoint-health"
  # Tickets
  /tickets:
    $ref: "./paths/tickets.yaml#/tickets"
  /tickets/{id}:
    $ref: "./paths/tickets.yaml#/ticket"
  /tickets/{id}/status:
    $ref: "./paths/tickets.yaml#/ticket-status"
  /tickets/{id}/priority:
    $ref: "./paths/tickets.yaml#/ticket-priority"
  /tickets/{id}/assign:
    $ref: "./paths/tickets.yaml#/ticket-assign"
  /tickets/{id}/comments:
    $ref: "./paths/tickets.yaml#/ticket-comments"
  /tickets/{id}/attachments:
    $ref: "./paths/tickets.yaml#/ticket-attachments"
  /tickets/{id}/sla-status:
    $ref: "./paths/tickets.yaml#/ticket-sla-status"
  /tickets/{id}/escalate:
    $ref: "./paths/tickets.yaml#/ticket-escalate"
  /tickets/{id}/timeline:
    $ref: "./paths/tickets.yaml#/ticket-timeline"
  /tickets/{id}/sla-times:
    $ref: "./paths/tickets.yaml#/ticket-sla-times"
  /tickets/{id}/pause-sla:
    $ref: "./paths/tickets.yaml#/ticket-pause-sla"
  /tickets/{id}/resume-sla:
    $ref: "./paths/tickets.yaml#/ticket-resume-sla"
  /tickets/{id}/exempt-sla:
    $ref: "./paths/tickets.yaml#/ticket-exempt-sla"
  # SLA Management
  /tickets/sla-policies:
    $ref: "./paths/tickets.yaml#/sla-policies"
  /tickets/sla-policies/{id}:
    $ref: "./paths/tickets.yaml#/sla-policy"
  /tickets/sla-breaches:
    $ref: "./paths/tickets.yaml#/sla-breaches"
  /tickets/near-breach:
    $ref: "./paths/tickets.yaml#/sla-near-breach"
  # Ticket Configuration
  /tickets/categories:
    $ref: "./paths/tickets.yaml#/ticket-categories"
  /tickets/priorities:
    $ref: "./paths/tickets.yaml#/ticket-priorities"
  /tickets/statuses:
    $ref: "./paths/tickets.yaml#/ticket-statuses"
  /tickets/tags:
    $ref: "./paths/tickets.yaml#/ticket-tags"

# 공통 컴포넌트
components:
  securitySchemes:
    bearerAuth:
      $ref: "./components/security.yaml#/bearerAuth"
